name: "Upload Artifact"
description: "Upload artifact to NAS"
inputs:
  id:
    description: "ID of file [--id value]"
    required: false
    default: ""
  path:
    description: "Path of file or directory"
    required: true
    default: ""
  zip:
    description: "Zip data [-z]"
    required: false
    default: ""
  output:
    description: "Output zip name [-o value]"
    required: false
    default: "-o artifact.zip"
  root:
    description: "Is root directory [-r]"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: "Get dart packages"
      run: dart pub get
    - name: "Zip and Deploy"
      run: dart bin/deploy.dart ${{ inputs.id }} ${{ inputs.zip }} ${{ inputs.output }} ${{ inputs.root }} ${{ inputs.path }}
