name: "Upload Artifact"
description: "Upload artifact to NAS"
inputs:
  id:
    description: "ID of file [--id value]"
    required: false
    default: ""
  path:
    description: "Path of file or directory"
    required: true
    default: ""
  zip:
    description: "Zip data [-z]"
    required: false
    default: ""
  output:
    description: "Output zip name [-o value]"
    required: false
    default: "-o artifact.zip"
  root:
    description: "Is root directory [-r]"
    required: false
    default: ""
runs:
  using: "node12"
  pre: "scripts/setup.js" # Delete this line to not run the setup script
  main: "scripts/index.js"
  post: "scripts/cleanup.js" # Delete this line to not run the cleanup script
